import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import Section from '@/components/section';
import type { Metadata } from "next";
import './globals.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen bg-bgPrimary">
        <Navbar />
        <Section>{children}</Section>
        <Footer />
      </body>
    </html>
  );
}
